### ISSUE TITLE
emoji 显示不正常

### ISSUE THREAD

**Issue by yeung66** [theme-next/hexo-filter-emoji#3]
![image](https://user-images.githubusercontent.com/22522618/76394908-36532000-63b1-11ea-9fb5-106c5b65bb43.png)

通过开发者工具把`background-image`属性禁掉，或者在style里面添加`background: none`，则显示正常。感觉是因为background-image导致emoji重复展示，但size又不一致。

**Comment by stevenjoezhang** [comment]
是的，已发布新版本 v2.1.1 包含此问题的修复

**Comment by yeung66** [comment]
更新版本v2.1.1后问题消失
