### ISSUE TITLE
emoji is incorrect on my web

### ISSUE THREAD

**Issue by ydfqdong** [theme-next/hexo-filter-emoji#4]
![text](https://alston-blog-1258129250.cos.ap-nanjing.myqcloud.com/about/emoji.png)

like this and what‘s wrong with bottom right-hand corner ?
i just followed the default deploy steps

thanks.

**Comment by stevenjoezhang** [comment]
Install the latest version
```
npm install hexo-filter-emoji@2.1.1
```

**Comment by ydfqdong** [comment]
it is effective，thanks a lot

**Comment by stevenjoezhang** [comment]
Have a nice day :)
