### ISSUE TITLE
数字类型的emoji显示不正常

### ISSUE THREAD

**Issue by yeung66** [theme-next/hexo-filter-emoji#5]
如图
![image](https://user-images.githubusercontent.com/22522618/77228251-f6fead80-6bc0-11ea-9a94-e2409f7f0c8c.png)
生成的代码如下
```html
<span class="github-emoji" data-alias="eight" style="" data-fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/0038-20e3.png?v8">8⃣</span>
```

**Comment by stevenjoezhang** [comment]
<img width="1128" alt="截屏2020-03-23下午4 31 15" src="https://user-images.githubusercontent.com/16272760/77297198-e31f8c80-6d23-11ea-8f97-2b6ae3151440.png">
这两个都是有效的 emoji，相差一个 \ufe0f 。

https://stackoverflow.com/questions/38100329/some-emojis-e-g-have-two-unicode-u-u2601-and-u-u2601-ufe0f-what-does

不便单独处理。

**Comment by yeung66** [comment]
但即使是前者也有点显示不正常吧

**Comment by stevenjoezhang** [comment]
欢迎 Pull Request ～

**Comment by yeung66** [comment]
开了一个[Pull Request](https://github.com/theme-next/hexo-filter-emoji/pull/6)
